# Check out https://docs.codemagic.io/getting-started/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    ios-app:
        name: Polymer
        environment:
            vars:
                XCODE_WORKSPACE: "Polymer"
                XCODE_SCHEME: "Scheme"
            flutter: stable
            xcode: latest
        scripts:
            - xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
            - xcode-project use-profiles
            - xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
            email:
                recipients:
                    - spameer.mee@gmail.com