name: project_polymer
description: Polymer is a state of the art app that allows students to reach their dream standardized scores. With high quality content written by high scoring individuals and advanced algorithms, Polymer is the fastest way to improve your test scores.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  provider: ^4.3.1
  material_design_icons_flutter: ^4.0.5855
  table_calendar: ^2.3.3
  google_fonts: ^1.1.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/

module:
  androidX: true